version: '3.8'

services:
  auth-server:
    build: ./auth-server
    ports:
      - "4000:4000"
    networks:
      - poc-network

  api-server:
    build: ./api-server
    ports:
      - "5001:5001"
    depends_on:
      - auth-server
    networks:
      - poc-network

  app-bff:
    build: ./app-bff
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
      - api-server
    networks:
      - poc-network

  app-spa:
    build: ./app-spa
    ports:
      - "3001:3001"
    depends_on:
      - auth-server
      - api-server
    networks:
      - poc-network

  app-web:
    build: ./app-web
    ports:
      - "3002:3002"
    depends_on:
      - auth-server
      - api-server
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
